repos:
  - repo: local
    hooks:
      - id: get_shared_config
        name: Get Shared Config
        entry: ./pre_commit_hooks/get_shared_config.sh
        language: script
        always_run: true

      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: system
        stages: [commit-msg]
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
