#!/usr/bin/env bash
set -eo pipefail
set -o errexit
set -o errtrace
shopt -s inherit_errexit

if [[ -f "./.git/hooks/pre-commit" ]]; then
    sh ./.git/hooks/pre-commit
fi

function tfdocu_do() {
    # terraform-docs will locate any available configuration file without needing to explicitly pass the --config flag.
    if [ -z "$TF_DOCS_CONF" ]; then
        if terraform-docs $1 > "$1/README.md"; then
            git add "$1/README.md"
        fi
    else
        if terraform-docs -c $TF_DOCS_CONF $1 > "$1/README.md"; then
            git add "$1/README.md"
        fi
    fi
}


# @description: iterates over all modules and triggers creation of tf docu
function tfdocu() {
    for dir in $(find . -maxdepth 1 -type d -not -path '*/.*' -not -path '.'); do
        echo $dir
        tfdocu_do $dir
    done

    if [[ -n "$(ls -A *.tf 2>/dev/null)" ]]; then
        tfdocu_do .
    fi
}


if [[ -n "$(ls -A *.tf 2>/dev/null)" || -n "$(find .  -maxdepth 2 -not -path '*/.*' -not -path '.' -type f -name '*.tf')" ]]; then
    tfdocu
fi