repos:
  - repo: https://gitlab.com/papanito/git-hooks.git
    rev: v2.2.2
    hooks:
      - id: get_shared_config
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  # Terraform stuff
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_trivy
  # Helm Stuff
  - repo: https://github.com/papanito/helm-pre-commit
    rev: main
    hooks:
      - id: helm-template-all
  # Ansible stuff
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.10.0  # Use the latest stable version
    hooks:
      - id: ansible-lint
        name: ansible-lint
        description: Run ansible-lint on Ansible files
        entry: ansible-lint
        language: python
        files: \.(yml|yaml)$
        # Exclude non-Ansible YAML files
        exclude: >-
          (?x)^(
            docker-compose\.yml|
            .github/.*|
            .pre-commit-config\.yaml
          )$
  # Python stuff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  # Go Stuff
  -   repo: https://github.com/tekwizely/pre-commit-golang
      # See 'pre-commit help autoupdate'
      rev: v1.0.0-rc.4
      hooks:
      #
      # Go Build
      #
      -   id: go-build-mod
      -   id: go-build-pkg
      -   id: go-build-repo-mod
      -   id: go-build-repo-pkg
      #
      # Go Tool (Go 1.24+)
      #
      -   id: go-tool
      -   id: go-tool-mod
      -   id: go-tool-repo
      -   id: go-tool-repo-mod
      #
      # Go Mod Tidy
      #
      -   id: go-mod-tidy
      -   id: go-mod-tidy-repo
      #
      # Go Test
      #
      -   id: go-test-mod
      -   id: go-test-pkg
      -   id: go-test-repo-mod
      -   id: go-test-repo-pkg
      #
      # Go Vet
      #
      -   id: go-vet
      -   id: go-vet-mod
      -   id: go-vet-pkg
      -   id: go-vet-repo-mod
      -   id: go-vet-repo-pkg
      #
      # Go Vulncheck
      # note: Only works with Go modules
      #
      -   id: go-vulncheck-mod
      -   id: go-vulncheck-repo-mod
      #
      # Revive
      #
      -   id: go-revive
      -   id: go-revive-mod
      -   id: go-revive-repo-mod
      #
      # GoSec
      #
      -   id: go-sec-mod
      -   id: go-sec-pkg
      -   id: go-sec-repo-mod
      -   id: go-sec-repo-pkg
      #
      # StaticCheck
      #
      -   id: go-staticcheck-mod
      -   id: go-staticcheck-pkg
      -   id: go-staticcheck-repo-mod
      -   id: go-staticcheck-repo-pkg
      #
      # StructSlop
      #
      -   id: go-structslop-mod
      -   id: go-structslop-pkg
      -   id: go-structslop-repo-mod
      -   id: go-structslop-repo-pkg
      #
      # Formatters
      #
      -   id: go-fmt
      -   id: go-fmt-repo
      -   id: go-fumpt        # replaces go-fmt
      -   id: go-fumpt-repo   # replaces go-fmt-repo
      -   id: go-imports      # replaces go-fmt
      -   id: go-imports-repo # replaces go-fmt-repo
      -   id: go-returns      # replaces go-imports & go-fmt
      -   id: go-returns-repo # replaces go-imports-repo & go-fmt-repo
      #
      # Style Checkers
      #
      -   id: go-lint
      -   id: go-critic
      #
      # GolangCI-Lint
      # - Fast Multi-Linter
      # - Can be configured to replace MOST other hooks
      # - Supports repo config file for configuration
      # - https://github.com/golangci/golangci-lint
      #
      -   id: golangci-lint
      -   id: golangci-lint-mod
      -   id: golangci-lint-pkg
      -   id: golangci-lint-repo-mod
      -   id: golangci-lint-repo-pkg
      #
      # Invoking Custom Go Tools
      # - Configured *entirely* through the `args` attribute, ie:
      #   args: [ go, test, ./... ]
      # - Use arg `--hook:error-on-output` to indicate that any output from the tool
      #   should be treated as an error.
      # - Use the `name` attribute to provide better messaging when the hook runs
      # - Use the `alias` attribute to be able to invoke your hook via `pre-commit run`
      #
      -   id: my-cmd
      -   id: my-cmd-mod
      -   id: my-cmd-pkg
      -   id: my-cmd-repo
      -   id: my-cmd-repo-mod
      -   id: my-cmd-repo-pkg
